[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
guard = "3SmBMUQe5QUpLc7wMrm97CRs3kXBSFtMZvPw8CDwZvUi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
